In [4]:
import numpy as np
matrix = np.arange(1, 10).reshape(3, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
operation_sum = lambda x: x + 101
operation_sum = np.vectorize(operation_sum)
print(operation_sum(matrix))

[[102 103 104]
 [105 106 107]
 [108 109 110]]


In [16]:
def debuck(x):
    return x-1 + x

In [17]:
debuck = np.vectorize(debuck)
print(debuck(matrix))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [26]:
ma = np.arange(12).reshape(4, 3)
ma.size

12

In [24]:
ma.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
matrix_2 =