In [3]:
import numpy as np

matrix_a = np.array([[1, 1, 1],
[1, 1, 1],
[1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
[1, 3, 1],
[1, 3, 8]])

In [4]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [5]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [6]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [7]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [8]:
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [9]:
matrix_a @ matrix_b # умножение матриц

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [10]:
matrix_a * matrix_b # поэлеметное умножение

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])