In [1]:
import numpy as np
matrix = np.arange(1, 17).reshape(4, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
matrix.diagonal()

array([ 1,  6, 11, 16])

In [4]:
matrix.diagonal(offset=1)

array([ 2,  7, 12])